export const COUNTRY_DATA = [
  { name: 'India', code: '+91', iso: 'IN' },
  { name: 'United States', code: '+1', iso: 'US' },
  { name: 'United Kingdom', code: '+44', iso: 'GB' },
  { name: 'United Arab Emirates', code: '+971', iso: 'AE' },
  { name: 'Australia', code: '+61', iso: 'AU' },
  { name: 'Canada', code: '+1', iso: 'CA' },
  { name: 'Germany', code: '+49', iso: 'DE' },
  { name: 'France', code: '+33', iso: 'FR' },
  { name: 'Singapore', code: '+65', iso: 'SG' },
  { name: 'Saudi Arabia', code: '+966', iso: 'SA' },
  { name: 'Oman', code: '+968', iso: 'OM' },
  { name: 'Kuwait', code: '+965', iso: 'KW' },
  { name: 'Qatar', code: '+974', iso: 'QA' },
  { name: 'Bahrain', code: '+973', iso: 'BH' },
  { name: 'Malaysia', code: '+60', iso: 'MY' },
  { name: 'New Zealand', code: '+64', iso: 'NZ' },
  { name: 'South Africa', code: '+27', iso: 'ZA' },
  { name: 'Brazil', code: '+55', iso: 'BR' },
  { name: 'Japan', code: '+81', iso: 'JP' },
  { name: 'China', code: '+86', iso: 'CN' },
  { name: 'Philippines', code: '+63', iso: 'PH' },
  { name: 'Thailand', code: '+66', iso: 'TH' },
  { name: 'Ireland', code: '+353', iso: 'IE' },
  { name: 'Italy', code: '+39', iso: 'IT' },
  { name: 'Spain', code: '+34', iso: 'ES' },
  { name: 'Netherlands', code: '+31', iso: 'NL' },
  { name: 'Switzerland', code: '+41', iso: 'CH' },
  { name: 'Norway', code: '+47', iso: 'NO' },
  { name: 'Sweden', code: '+46', iso: 'SE' },
  { name: 'Denmark', code: '+45', iso: 'DK' },
];
